name: iginfo
description: "App informativa para iglesia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Agregar para HTTP requests
  http: ^1.2.0
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  
  # UI y utilidades
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  timeago: ^3.7.0
  
  # Compartir contenido
  share_plus: ^10.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Aquí irán tus assets más adelante
  # assets:
  #   - assets/images/
  #   - assets/icons/