// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-N4vqxIJoTIoVlVgHTAIQExztol2iOAU',
    appId: '1:200768940489:web:554ae71c6ba0ec1a702018',
    messagingSenderId: '200768940489',
    projectId: 'db-church',
    authDomain: 'db-church.firebaseapp.com',
    storageBucket: 'db-church.firebasestorage.app',
    measurementId: 'G-7Q0H40X00V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKRHdGeSNDa0W4QzxAn3vBLb40OKNRvo',
    appId: '1:200768940489:android:ddd41a01cd9bc52f702018',
    messagingSenderId: '200768940489',
    projectId: 'db-church',
    storageBucket: 'db-church.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7eZmcf0Mp6LjzCGvGOxN-CJta-QPBTwg',
    appId: '1:200768940489:ios:f2f8a0873bb9fc83702018',
    messagingSenderId: '200768940489',
    projectId: 'db-church',
    storageBucket: 'db-church.firebasestorage.app',
    iosBundleId: 'com.example.iginfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7eZmcf0Mp6LjzCGvGOxN-CJta-QPBTwg',
    appId: '1:200768940489:ios:f2f8a0873bb9fc83702018',
    messagingSenderId: '200768940489',
    projectId: 'db-church',
    storageBucket: 'db-church.firebasestorage.app',
    iosBundleId: 'com.example.iginfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-N4vqxIJoTIoVlVgHTAIQExztol2iOAU',
    appId: '1:200768940489:web:c14fdc12e04724a3702018',
    messagingSenderId: '200768940489',
    projectId: 'db-church',
    authDomain: 'db-church.firebaseapp.com',
    storageBucket: 'db-church.firebasestorage.app',
    measurementId: 'G-J9R62ZLJH2',
  );
}
